# Generated by Django 5.1.4 on 2025-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_order_orderitem_shippinginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
